<?php
$z[0]=Array("arcurl","",46,61);
$z[1]=Array("fulltitle","",87,105);
$z[2]=Array("litpic","",119,134);
$z[3]=Array("fulltitle","",141,159);
$z[4]=Array("fulltitle","",169,187);
$z[5]=Array("arcurl","",223,238);
$z[6]=Array("fulltitle","",264,282);
$z[7]=Array("title","",286,300);
$z[8]=Array("description","",314,364);
$z[8][4]['function']="cn_substr(@me,100)";
$z[9]=Array("arcurl","",388,403);

?>