<dl class="new_about clearfix">
                    <dt><a href="[field:arcurl/]" target="_blank"
                        title="[field:fulltitle/]">
                        <img src="[field:litpic/]" alt="[field:fulltitle/]"
                            title="[field:fulltitle/]" /></a></dt>
                    <dd>
                        <h2>
                            <a href="[field:arcurl/]" target="_blank"
                                title="[field:fulltitle/]">
                                [field:title/]</a></h2>
                        <p>[field:description function="cn_substr(@me,100)"/]...</p>
                        <span><a href="[field:arcurl/]" target="_blank"
                            title="[查看详情]">[查看详情]</a></span>
                    </dd>
                </dl>