<?php
$z[0]=Array("arcurl","",66,81);
$z[1]=Array("fulltitle","",131,149);
$z[2]=Array("litpic","",187,202);
$z[3]=Array("fulltitle","",209,227);
$z[4]=Array("fulltitle","",265,283);
$z[5]=Array("arcurl","",391,406);
$z[6]=Array("fulltitle","",464,482);
$z[7]=Array("title","",518,532);
$z[8]=Array("description","",570,620);
$z[8][4]['function']="cn_substr(@me,100)";
$z[9]=Array("arcurl","",668,683);

?>