<dl class="news_dl">
                                <dt><a href="[field:arcurl/]" target="_blank"
                                    title="[field:fulltitle/]" class="dt_1">
                                   [field:fulltitle/] </a><span class="dt_2">[
                                        [field:pubdate function=MyDate('Y-m-d',@me)/]
                                        ]</span></dt>
                                <dd>
                                 [field:description function="cn_substr(@me,450)"/]...</dd>
                            </dl>