
<field:lxr itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>

<field:tel1 itemname="电话区号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel1>

<field:tel2 itemname="座机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel2>

<field:tel3 itemname="分机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel3>

<field:mob itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mob>

<field:email itemname="电子邮件" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:mytime itemname="提交时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mytime>
