<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/150419/1-150419155Z3.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/150419/1-150419155Z3-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="519";
$z[2]=Array("img"," /uploads/allimg/151004/1-151004191442.jpg ",243,393);
$z[2][4]['ddimg']="/uploads/allimg/151004/1-151004191442-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="467";
$z[2][4]['height']="324";
$z[3]=Array("img"," /uploads/allimg/151004/1-151004191443.jpg ",395,545);
$z[3][4]['ddimg']="/uploads/allimg/151004/1-151004191443-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="327";
$z[3][4]['height']="242";

?>