<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/150418/1-15041R14G6.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150418/1-15041R14G6-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="900";
$z[1][4]['height']="600";
$z[2]=Array("img"," /uploads/allimg/150418/1-15041R14G6-50.jpg ",241,393);
$z[2][4]['ddimg']="/uploads/allimg/150418/1-15041R14G6-50-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="900";
$z[2][4]['height']="600";
$z[3]=Array("img"," /uploads/allimg/150418/1-15041R14G6-51.jpg ",395,547);
$z[3][4]['ddimg']="/uploads/allimg/150418/1-15041R14G6-51-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="900";
$z[3][4]['height']="600";

?>