{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='3'/}
{dede:img ddimg='/uploads/allimg/150418/1-15041R14G6-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R14G6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R14G6-50-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R14G6-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R14G6-51-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R14G6-51.jpg {/dede:img}
