<dl class="dl_h3_1">
                                <dt><a href="[field:arcurl/]" target="_blank"
                                    title="[field:fulltitle/]">
                                    <img src="[field:litpic/]" title="[field:fulltitle/]"
                                        alt="[field:fulltitle/]" /></a></dt>
                                <dd>
                                    <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">
                                       [field:title/]</a></dd>
                            </dl>