<dl class="dl_3_2">
                                <dt><a href="[field:arcurl/]" title="[field:fulltitle/]"  target="_blank">
                                    <img src="[field:litpic/]" title="[field:fulltitle/]" alt="[field:fulltitle/]" /></a></dt>
                                <dd>
                                    <a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:title/]</a></dd>
                            </dl>