<dl id='bigGri[field:global.autoindex/]' onmousemove='showsmallG([field:global.autoindex/])'>
				<dt id='smallDT[field:global.autoindex/]'><span>[field:global.autoindex/]</span><a title='[field:fulltitle/]' target="_blank" href='[field:arcurl/]'>[field:title/]</a></dt>
				<dd style="display: none" id='smallG[field:global.autoindex/]'><span class="shuz">[field:global.autoindex/]</span><div class="img02"><a title='[field:fulltitle/]' target="_blank" href='[field:arcurl/]'><img title='[field:fulltitle/]' src='[field:litpic/]' /></a></div><div class="zi1"><a title='[field:fulltitle/]' target="_blank" href='[field:arcurl/]'>[field:title/]</a></div><div class="zi2"></div><div class="clear"></div>
				</dd>
				</dl>