<?php
$z[0]=Array("global","\r\nif(@me%2==0)@me=\"<dl class=' case_pic clearfix nobd fr'>\";\r\nelse @me=\" <dl class=' case_pic clearfix nobd fl'>\";\r\n",0,173);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",250,265);
$z[2]=Array("fulltitle","",319,337);
$z[3]=Array("litpic","",379,394);
$z[4]=Array("fulltitle","",434,452);
$z[5]=Array("fulltitle","",461,479);
$z[6]=Array("arcurl","",587,602);
$z[7]=Array("fulltitle","",660,678);
$z[8]=Array("title","",680,694);
$z[9]=Array("description","",732,782);
$z[9][4]['function']="cn_substr(@me,100)";
$z[10]=Array("arcurl","",830,845);

?>