<?php
$z[0]=Array("global","\r\nif(@me%2==0)@me=\"<dl class=' case_pic clearfix nobd fr'>\";\r\nelse @me=\" <dl class=' case_pic clearfix nobd fl'>\";\r\n",0,173);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",192,207);
$z[2]=Array("fulltitle","",233,251);
$z[3]=Array("litpic","",265,280);
$z[4]=Array("fulltitle","",288,306);
$z[5]=Array("fulltitle","",315,333);
$z[6]=Array("arcurl","",369,384);
$z[7]=Array("fulltitle","",410,428);
$z[8]=Array("title","",430,444);
$z[9]=Array("description","",458,508);
$z[9][4]['function']="cn_substr(@me,100)";
$z[10]=Array("arcurl","",532,547);

?>