<?php
$z[0]=Array("global","\r\nif(@me%3==0)@me=\"<dl  class='hot_pro nomg'>\";\r\nelse @me=\" <dl  class='hot_pro '>\";\r\n",0,143);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",158,173);
$z[2]=Array("fulltitle","",208,226);
$z[3]=Array("litpic","",246,261);
$z[4]=Array("fulltitle","",271,289);
$z[5]=Array("fulltitle","",301,319);
$z[6]=Array("arcurl","",357,372);
$z[7]=Array("fulltitle","",411,429);
$z[8]=Array("title","",431,445);

?>