[field:global name=autoindex runphp="yes"]
if(@me%3==0)@me="<dl  class='hot_pro nomg'>";
else @me=" <dl  class='hot_pro '>";
[/field:global]
<dt><a href="[field:arcurl/]" target="_blank"
      title="“[field:fulltitle/]">
      <img src="[field:litpic/]" alt="“[field:fulltitle/]" title="“[field:fulltitle/]" /></a></dt>
  <dd>
      <a href="[field:arcurl/]" target="_blank"
          title="“[field:fulltitle/]">[field:title/]</a></dd>
</dl>