<dl class="pd_list_dl">
                                <dt><a href="[field:arcurl/]" target="_blank"
                                    title="[field:fulltitle/]">
                                    <img src="[field:litpic/]" alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a></dt>
                                <dd>
                                    <a href="[field:arcurl/]" title="[field:fulltitle/]"
                                        target="_blank">[field:title/]</a></dd>
                            </dl>