<?php
$z[0]=Array("global","\r\nif(@me%3==0)@me=\"<dl  class='hot_pro nomg'>\";\r\nelse @me=\"<dl  class='hot_pro '>\";\r\n",0,142);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",159,174);
$z[2]=Array("fulltitle","",200,218);
$z[3]=Array("litpic","",251,266);
$z[4]=Array("fulltitle","",274,292);
$z[5]=Array("fulltitle","",301,319);
$z[6]=Array("arcurl","",349,364);
$z[7]=Array("fulltitle","",390,408);
$z[8]=Array("title","",412,426);

?>