<?php
$z[0]=Array("global","",181,207);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",248,270);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",310,361);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",525,583);
$z[4]=Array("field","",645,667);
$z[4][4]['name']="position";
$z[5]=Array("field","",710,729);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist"," \r\n<div class=\"swiper-slide\"> <img src=\"[field:imgsrc/]\" title=\"[field:text/]\" alt=\"[field:text/]\"> </div>							\r\n",961,1123);
$z[7]=Array("field","",1746,1764);
$z[7][4]['name']="body";
$z[8]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",1810,1870);

?>