<?php
$z[0]=Array("field","",325,344);
$z[0][4]['name']="title";
$z[1]=Array("global","",345,371);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",412,441);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",481,540);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1631,1666);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n		<li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n	    ",2102,2290);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("include","",2321,2362);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",2455,2484);
$z[7][4]['name']="position";
$z[8]=Array("field","",2647,2665);
$z[8][4]['name']="body";
$z[9]=Array("include","",2850,2887);
$z[9][4]['filename']="footer.htm";

?>