<?php
$z[0]=Array("global","\r\nif(@me%3==0)@me=\"<dl  class='hot_pro nomg'>\";\r\nelse @me=\" <dl  class='hot_pro '>\";\r\n",0,143);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",212,227);
$z[2]=Array("fulltitle","",292,310);
$z[3]=Array("litpic","",360,375);
$z[4]=Array("fulltitle","",385,403);
$z[5]=Array("fulltitle","",415,433);
$z[6]=Array("arcurl","",531,546);
$z[7]=Array("fulltitle","",615,633);
$z[8]=Array("title","",635,649);

?>