<?php
$z[0]=Array("global","\r\nif(@me%3==0)@me=\"<dl  class='hot_pro nomg'>\";\r\nelse @me=\" <dl  class='hot_pro '>\";\r\n",0,143);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",187,202);
$z[2]=Array("fulltitle","",267,285);
$z[3]=Array("litpic","",335,350);
$z[4]=Array("fulltitle","",360,378);
$z[5]=Array("fulltitle","",390,408);
$z[6]=Array("arcurl","",506,521);
$z[7]=Array("fulltitle","",590,608);
$z[8]=Array("title","",610,624);

?>