{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='3'/}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21P1-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R21P1.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21P1-50-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R21P1-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21P1-51-lp.jpg' text='' width='900' height='660'} /uploads/allimg/150418/1-15041R21P1-51.jpg {/dede:img}
