<dl class="coop_dl ">
                                    <dt><a href="[field:arcurl/]" target="_blank"
                                        title="[field:fulltitle/]">
                                        <img class="classname" src="[field:litpic/]"
                                            alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a></dt>
                                    <dd>
                                        <div class="cptx1">
                                            <h3>
                                                <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">产品名称：[field:title/]</a></h3>
                                            <p class="fun_tx">
                                                [field:description function="cn_substr(@me,400)"/]...</p>
                                            <p class="fun_a">
                                                <a href="[field:arcurl/]" target="_blank" title="[查看详情]">[查看详情]</a></p>
                                            <div class="fun_tel clearfix">
                                                <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=125737369&site=立即咨询"
                                                    title="立即咨询" class="ft_btn fr">
                                                    <img src="/statics/images/btn_01.gif" title="立即咨询" alt="立即咨询" /></a>
                                                <div class="ft_tx fr">
                                                   服务热线<br />
                                                    <span>400-800-8888</span></div>
                                            </div>
                                        </div>
                                        <ul class="cptx2 ">
                                            
                                        </ul>
                                    </dd>
                                </dl>