<?php
$z[0]=Array("arcurl","",72,87);
$z[1]=Array("fulltitle","",153,171);
$z[2]=Array("litpic","",243,258);
$z[3]=Array("fulltitle","",310,328);
$z[4]=Array("fulltitle","",337,355);
$z[5]=Array("arcurl","",580,595);
$z[6]=Array("fulltitle","",620,638);
$z[7]=Array("title","",655,669);
$z[8]=Array("description","",792,842);
$z[8][4]['function']="cn_substr(@me,400)";
$z[9]=Array("arcurl","",971,986);

?>