<?php
$z[0]=Array("global","\r\nif(@me%3==0)@me=\"<dl  class='hot_pro nomg'>\";\r\nelse @me=\"<dl  class='hot_pro '>\";\r\n",0,142);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",179,194);
$z[2]=Array("fulltitle","",244,262);
$z[3]=Array("litpic","",319,334);
$z[4]=Array("fulltitle","",370,388);
$z[5]=Array("fulltitle","",397,415);
$z[6]=Array("arcurl","",489,504);
$z[7]=Array("fulltitle","",558,576);
$z[8]=Array("title","",608,622);

?>