{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='3'/}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21I8-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R21I8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21I8-50-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R21I8-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150418/1-15041R21I9-lp.jpg' text='' width='900' height='600'} /uploads/allimg/150418/1-15041R21I9.jpg {/dede:img}
