<dl class="dl_42">
                                <dt><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">
                                    <img src="[field:litpic/]" title="[field:fulltitle/]"
                                        alt="[field:fulltitle/]" /></a></dt>
                                <dd>
                                    <h4>
                                        <a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">
                                        [field:title/]</a></h4>
                                    [field:description function="cn_substr(@me,300)"/]...
                                </dd>
                            </dl>
                            <div class="clear">
                            </div>