
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="备注留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:mytime itemname="提交时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mytime>
