<dl class="pro_pic">
                            <dt><a href="[field:arcurl/]" target="_blank"
                                title="[field:fulltitle/]">
                                <img class="classname" _src="[field:litpic/]"
                                    alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a></dt>
                            <dd>
                                <a href="[field:arcurl/]" target="_blank"
                                    title="[field:fulltitle/]">
                                    [field:title/]</a></dd>
                        </dl>