<?php
$z[0]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",70,164);
$z[0][4]['typeid']="2";
$z[1]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",168,262);
$z[1][4]['typeid']="3";
$z[2]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",266,360);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",364,458);
$z[3][4]['typeid']="5";
$z[4]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",462,557);
$z[4][4]['typeid']="24";
$z[5]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",561,656);
$z[5][4]['typeid']="49";
$z[6]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",660,755);
$z[6][4]['typeid']="50";
$z[7]=Array("global","",800,826);
$z[7][4]['name']="cfg_address";
$z[8]=Array("global","",850,872);
$z[8][4]['name']="cfg_tel";
$z[9]=Array("global","",893,914);
$z[9][4]['name']="cfg_qq";

?>