<?php
$z[0]=Array("global","",551,574);
$z[0][4]['name']="cfg_mail";
$z[1]=Array("global","",611,633);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",652,678);
$z[2][4]['name']="cfg_address";
$z[3]=Array("global","",759,781);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",945,969);
$z[4][4]['name']="cfg_qqone";
$z[5]=Array("global","",996,1020);
$z[5][4]['name']="cfg_qqtwo";
$z[6]=Array("global","",1058,1084);
$z[6][4]['name']="cfg_qqthree";

?>