<?php
$z[0]=Array("global","",530,553);
$z[0][4]['name']="cfg_mail";
$z[1]=Array("global","",590,612);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",631,657);
$z[2][4]['name']="cfg_address";
$z[3]=Array("global","",738,760);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",924,948);
$z[4][4]['name']="cfg_qqone";
$z[5]=Array("global","",975,999);
$z[5][4]['name']="cfg_qqtwo";
$z[6]=Array("global","",1037,1063);
$z[6][4]['name']="cfg_qqthree";

?>