<?php
$z[0]=Array("global","",444,471);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1171,1193);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("type","<li><a href=\"[field:typeurl/]\"><span>产品中心</span></a></li>",1448,1547);
$z[2][4]['typeid']="2";
$z[3]=Array("type","<li><a href=\"[field:typeurl/]\"><span>客户案例</span></a></li>",1549,1648);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<li><a href=\"[field:typeurl/]\"><span>关于我们</span></a></li>",1650,1749);
$z[4][4]['typeid']="1";
$z[5]=Array("type","<li><a href=\"[field:typeurl/]\"><span>新闻资讯</span></a></li>",1751,1850);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<li><a href=\"[field:typeurl/]\"><span>公司相册</span></a></li>",1852,1951);
$z[6][4]['typeid']="8";
$z[7]=Array("type","<li><a href=\"[field:typeurl/]\"><span>常见问题</span></a></li>",1953,2053);
$z[7][4]['typeid']="24";
$z[8]=Array("type","<li><a href=\"[field:typeurl/]\"><span>联系我们</span></a></li>",2055,2155);
$z[8][4]['typeid']="49";
$z[9]=Array("type","<li class=\"nobg\"><a href=\"[field:typeurl/]\"><span>在线留言</span></a></li>",2157,2270);
$z[9][4]['typeid']="50";
$z[10]=Array("tag","\r\n<a href='[field:link/]'>[field:tag /]</a>\r\n",2435,2534);
$z[10][4]['row']="10";
$z[10][4]['getall']="1";
$z[10][4]['sort']="month";
$z[11]=Array("global","",2609,2634);
$z[11][4]['name']="cfg_cmsurl";

?>