<?php
$z[0]=Array("global","",130,152);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",246,340);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",351,445);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",456,550);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",561,655);
$z[4][4]['typeid']="5";
$z[5]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",666,761);
$z[5][4]['typeid']="24";
$z[6]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",772,867);
$z[6][4]['typeid']="49";
$z[7]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">[field:typename/]</a>",878,973);
$z[7][4]['typeid']="50";

?>