<?php
$z[0]=Array("global","",306,333);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",861,888);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1573,1595);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("type","<li><a href=\"[field:typeurl/]\"><span>产品中心</span></a></li>",1852,1951);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<li><a href=\"[field:typeurl/]\"><span>客户案例</span></a></li>",1953,2052);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<li><a href=\"[field:typeurl/]\"><span>关于我们</span></a></li>",2054,2153);
$z[5][4]['typeid']="1";
$z[6]=Array("type","<li><a href=\"[field:typeurl/]\"><span>新闻资讯</span></a></li>",2155,2254);
$z[6][4]['typeid']="5";
$z[7]=Array("type","<li><a href=\"[field:typeurl/]\"><span>公司相册</span></a></li>",2256,2355);
$z[7][4]['typeid']="8";
$z[8]=Array("type","<li><a href=\"[field:typeurl/]\"><span>常见问题</span></a></li>",2357,2457);
$z[8][4]['typeid']="24";
$z[9]=Array("type","<li><a href=\"[field:typeurl/]\"><span>联系我们</span></a></li>",2459,2559);
$z[9][4]['typeid']="49";
$z[10]=Array("type","<li class=\"nobg\"><a href=\"[field:typeurl/]\"><span>在线留言</span></a></li>",2561,2674);
$z[10][4]['typeid']="50";

?>