<?php
$z[0]=Array("global","",178,204);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",248,278);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",315,342);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",666,724);
$z[4]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">更多>></a>",1378,1463);
$z[4][4]['typeid']="1";
$z[5]=Array("sql","\r\n\r\n[field:content function='cn_substr(html2text(@me),300)'/]\r\n\r\n",1548,1684);
$z[5][4]['sql']="Select content from dede_arctype where id=9";
$z[6]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">更多>></a>",1764,1849);
$z[6][4]['typeid']="2";
$z[7]=Array("arclist","\r\n<li><a href=\"/wapview.php?aid=[field:id/]\"><img src=\"[field:litpic/]\"/><span>[field:title/]</span></a></li>\r\n",1862,2021);
$z[7][4]['typeid']="2";
$z[7][4]['row']="6";
$z[8]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">更多>></a>",2094,2179);
$z[8][4]['typeid']="5";
$z[9]=Array("arclist","\r\n<li><i>[[field:typename/]]</i><a href=\"/wapview.php?aid=[field:id/]\">[field:title/]</a><em>[field:pubdate function=MyDate('m-d',@me)/]</em></li>\r\n",2192,2403);
$z[9][4]['typeid']="5";
$z[9][4]['titlelen']="45";
$z[9][4]['row']="10";
$z[10]=Array("type","<a href=\"/waplist.php?tid=[field:id/]\">更多>></a>",2477,2562);
$z[10][4]['typeid']="3";
$z[11]=Array("arclist","\r\n<li><a href=\"/wapview.php?aid=[field:id/]\"><img src=\"[field:litpic/]\"/><span>[field:title/]</span></a></li>\r\n",2575,2734);
$z[11][4]['typeid']="3";
$z[11][4]['row']="6";
$z[12]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",2761,2821);

?>