<?php
$z[0]=Array("field","",263,282);
$z[0][4]['name']="title";
$z[1]=Array("global","",283,309);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",350,379);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",419,478);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1121,1156);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n		<li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n	    ",1642,1830);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("include","",1854,1895);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",1983,2012);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                    \r\n                            <dl class=\"dl_h3\">\r\n                                <dt><a href=\"[field:arcurl/]\" target=\"_blank\"\r\n                                    title=\"[field:fulltitle/]\">\r\n                                    <img src=\"[field:litpic/]\" title=\"[field:fulltitle/]\"\r\n                                        alt=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></dd>\r\n                            </dl>\r\n                   \r\n                           ",2274,2948);
$z[8][4]['pagesize']="12";
$z[9]=Array("pagelist","",3088,3159);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3377,3414);
$z[10][4]['filename']="footer.htm";

?>