<?php
$z[0]=Array("field","",267,286);
$z[0][4]['name']="title";
$z[1]=Array("global","",287,313);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",354,383);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",423,482);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1125,1160);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n		<li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n	    ",1687,1875);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("include","",1905,1946);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",2034,2063);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                            <dl class=\"dl_3\">\r\n                                <dt><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">\r\n                                    <img src=\"[field:litpic/]\" title=\"[field:fulltitle/]\" alt=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></dd>\r\n                            </dl>\r\n							 \r\n                         ",2186,2746);
$z[8][4]['pagesize']="20";
$z[9]=Array("pagelist","",2951,3022);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("arclist"," \r\n                            <dl class=\"pd_list_dl\">\r\n                                <dt><a href=\"[field:arcurl/]\" target=\"_blank\"\r\n                                    title=\"[field:fulltitle/]\">\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" title=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"\r\n                                        target=\"_blank\">[field:title/]</a></dd>\r\n                            </dl>\r\n                        ",3278,3948);
$z[10][4]['typeid']="2";
$z[10][4]['titlelen']="24";
$z[10][4]['row']="4";
$z[10][4]['orderby']="click";
$z[11]=Array("include","",4253,4290);
$z[11][4]['filename']="footer.htm";

?>