<?php
$z[0]=Array("field","",265,284);
$z[0][4]['name']="title";
$z[1]=Array("global","",285,311);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",352,381);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",421,480);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1123,1158);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n		<li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n	    ",1685,1873);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("include","",1898,1939);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",2025,2054);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                            <dl class=\"dl_3_1\">\r\n                                <dt><a>\r\n                                    <img src=\"[field:litpic/]\" title=\"[field:fulltitle/]\" alt=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a>[field:title/]</a></dd>\r\n                            </dl>\r\n                       ",2179,2597);
$z[8][4]['pagesize']="20";
$z[9]=Array("arclist"," \r\n                            <dl class=\"pd_list_dl\">\r\n                                <dt><a href=\"[field:arcurl/]\" target=\"_blank\"\r\n                                    title=\"[field:fulltitle/]\">\r\n                                    <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" title=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"\r\n                                        target=\"_blank\">[field:title/]</a></dd>\r\n                            </dl>\r\n                        ",2953,3623);
$z[9][4]['typeid']="2";
$z[9][4]['titlelen']="24";
$z[9][4]['row']="4";
$z[9][4]['orderby']="click";
$z[10]=Array("include","",5545,5582);
$z[10][4]['filename']="footer.htm";

?>