<?php
$z[0]=Array("field","",265,284);
$z[0][4]['name']="title";
$z[1]=Array("global","",285,311);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",352,381);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",421,480);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1123,1158);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1706,1747);
$z[5][4]['filename']="lr_contact.htm";
$z[6]=Array("field","",1829,1858);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                            <dl class=\"dl_3_2\">\r\n                                <dt><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"  target=\"_blank\">\r\n                                    <img src=\"[field:litpic/]\" title=\"[field:fulltitle/]\" alt=\"[field:fulltitle/]\" /></a></dt>\r\n                                <dd>\r\n                                    <a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></dd>\r\n                            </dl>\r\n                         ",1981,2533);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2711,2782);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",4610,4647);
$z[9][4]['filename']="footer.htm";

?>