<?php
$z[0]=Array("field","",328,347);
$z[0][4]['name']="title";
$z[1]=Array("global","",348,374);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",415,444);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",484,543);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1547,1582);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","if(@me=='49')@me='<li class=\"cur\"><a href=\"/contact/\" >';else@me='<li><a href=\"/contact/\">';\r\n",2049,2220);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[5][4]['function']="GetTopid(@me)";
$z[6]=Array("include","",2288,2329);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",2422,2451);
$z[7][4]['name']="position";
$z[8]=Array("field","",2614,2635);
$z[8][4]['name']="content";
$z[9]=Array("include","",2986,3023);
$z[9][4]['filename']="footer.htm";

?>