<?php
$z[0]=Array("global","",178,204);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",245,274);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",314,372);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",649,707);
$z[4]=Array("field","",769,791);
$z[4][4]['name']="position";
$z[5]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",3153,3213);

?>