<?php
$z[0]=Array("field","",328,347);
$z[0][4]['name']="title";
$z[1]=Array("global","",348,374);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",415,444);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",484,543);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1638,1673);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2114,2143);
$z[5][4]['name']="position";
$z[6]=Array("channelartlist","\r\n<h4>\r\n<a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\" target=\"_blank\">{dede:field name='typename'/}</a>\r\n</h4>\r\n<div class=\"b4\">\r\n<ul>\r\n{dede:channel type='son' }\r\n<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a></li>\r\n{/dede:channel}\r\n</ul>\r\n<div class=\"clear\"></div>\r\n</div>\r\n",2163,2609);
$z[6][4]['typeid']="1,2,4,29,5,6,20,39,50,32,64";
$z[6][4]['row']="99999";
$z[7]=Array("include","",2745,2782);
$z[7][4]['filename']="footer.htm";

?>