<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1471,1506);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","if(@me=='50')@me='<li class=\"cur\"><a href=\"/message/\" >';else@me='<li><a href=\"/message/\">';\r\n",2020,2191);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[5][4]['function']="GetTopid(@me)";
$z[6]=Array("include","",2254,2295);
$z[6][4]['filename']="lr_contact.htm";
$z[7]=Array("field","",2385,2414);
$z[7][4]['name']="position";
$z[8]=Array("include","",9097,9134);
$z[8][4]['filename']="footer.htm";

?>