<?php
$z[0]=Array("global","",178,204);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",245,274);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",314,372);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",543,601);
$z[4]=Array("field","",663,685);
$z[4][4]['name']="position";
$z[5]=Array("field","",726,747);
$z[5][4]['name']="content";
$z[6]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",774,834);

?>