<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-10-04 18:53:16
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=50&mid=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-01-02 22:06:02
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-12-22 15:47:42
*/
?>
